/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ffmpeg_MainActivity */

#ifndef _Included_com_example_ffmpeg_MainActivity
#define _Included_com_example_ffmpeg_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ffmpeg_MainActivity
 * Method:    ffmpeg_decode
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_example_ffmpeg_MainActivity_ffmpeg_1decode
  (JNIEnv *, jclass);

/*
 * Class:     com_example_ffmpeg_MainActivity
 * Method:    ffmpeg_encode
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_example_ffmpeg_MainActivity_ffmpeg_1encode
  (JNIEnv *, jclass);

/*
 * Class:     com_example_ffmpeg_MainActivity
 * Method:    ffmpeg_pcm_aac
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_example_ffmpeg_MainActivity_ffmpeg_1pcm_1aac
  (JNIEnv *, jclass);

/*
 * Class:     com_example_ffmpeg_MainActivity
 * Method:    ffmpeg_yuv_h264
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_example_ffmpeg_MainActivity_ffmpeg_1yuv_1h264
  (JNIEnv *, jclass);

/*
 * Class:     com_example_ffmpeg_MainActivity
 * Method:    ffmpeg_mp4_mkv
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_example_ffmpeg_MainActivity_ffmpeg_1mp4_1mkv
  (JNIEnv *, jclass);

/*
 * Class:     com_example_ffmpeg_MainActivity
 * Method:    ffmpeg_merge
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_example_ffmpeg_MainActivity_ffmpeg_1merge
  (JNIEnv *, jclass);

/*
 * Class:     com_example_ffmpeg_MainActivity
 * Method:    ffmpeg_remuder
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_example_ffmpeg_MainActivity_ffmpeg_1remuxer
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
